"""Add is_processed flag

Revision ID: 28f4208371fb
Revises: 6ae5d0b4ff03
Create Date: 2026-09-30 13:34:10.194253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f4208371fb'
down_revision: Union[str, Sequence[str], None] = '6ae5d0b4ff03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_data', sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('google_news_articles', sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('youtube_videos', sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_videos', 'is_processed')
    op.drop_column('google_news_articles', 'is_processed')
    op.drop_column('github_data', 'is_processed')
    # ### end Alembic commands ###
