"""add_marketing_tables

Revision ID: 6ae5d0b4ff03
Revises: f91cfce6467e
Create Date: 2026-09-30 11:00:10.031338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae5d0b4ff03'
down_revision: Union[str, Sequence[str], None] = 'f91cfce6467e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_label', sa.String(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sources', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('avg_engagement_score', sa.Float(), nullable=False),
    sa.Column('item_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('campaign_type', sa.String(), nullable=False),
    sa.Column('topic_label', sa.String(), nullable=False),
    sa.Column('hook', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('cta', sa.String(), nullable=True),
    sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['content_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketing_campaigns')
    op.drop_table('content_clusters')
    # ### end Alembic commands ###
