"""add_config_tables

Revision ID: f91cfce6467e
Revises: 5d4e39392e91
Create Date: 2026-09-29 17:39:33.489173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91cfce6467e'
down_revision: Union[str, Sequence[str], None] = '5d4e39392e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_search_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('days_active', sa.Integer(), nullable=True),
    sa.Column('min_stars', sa.Integer(), nullable=True),
    sa.Column('min_forks', sa.Integer(), nullable=True),
    sa.Column('require_license', sa.Boolean(), nullable=True),
    sa.Column('selected_topics', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('selected_languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('last_search_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_news_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q', sa.String(), nullable=False),
    sa.Column('hl', sa.String(), nullable=True),
    sa.Column('gl', sa.String(), nullable=True),
    sa.Column('ceid', sa.String(), nullable=True),
    sa.Column('when', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('intitle', sa.String(), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('last_search_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_search_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('channel_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('last_search_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_search_config')
    op.drop_table('google_news_config')
    op.drop_table('github_search_config')
    # ### end Alembic commands ###
