from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal


@dataclass
class MarketingCampaign:
    """
    A marketing campaign generated by the LLM for a specific content cluster.
    Targets B2B / consulting firm audiences.
    """

    id: str                                              # UUID4
    cluster_id: int | None
    topic_label: str
    campaign_type: Literal["linkedin_post", "twitter_thread", "email_newsletter"]
    hook: str | None                                     # Attention-grabbing first line
    body: str                                            # Main content
    cta: str | None                                      # Call to action
    hashtags: list[str] = field(default_factory=list)
    status: Literal["draft", "approved", "published"] = "draft"
    created_at: datetime | None = None
